### ISSUE TITLE
Create matching code

### ISSUE THREAD

**Issue by mbellgb** [mbellgb/syseng19-code#26]
Here's some pseudo code for how this could be applied to a `Cohort` object.

```python
def match(self):
  pairings = []
  # Select all mentees, create a MentorshipScore object for each mentor.
  mentors = self.participants.filter(isMentor=True)
  for mentee in self.participants.filter(isMentor=False):
    for mentor in mentors:
      p = MentorshipScore.objects.create(\
        mentor=mentor,
        mentee=mentee,
      )
      pairings.append(p)

  # now let's work out how compatible each match is an assign them scores.
  for p in pairings:
    mentee_tags = list(p.mentee.tags.all())
    mentor_tags = list(p.mentor.tags.all())
    p.score = len(set(mentee_tags).intersection(mentor_tags))
    p.save()

# given a participant, get a list of their preferred matches.
def get_preferred_matches(self):
  matches = []
  if not self.isMentor:
    return list(MentorshipScore.objects.filter(mentee=self).order_by('-score'))
  # only mentees will be able to select preferences.
  return []
```

**Comment by harrychen0702** [comment]
Not really understand the  "return list(MentorshipScore.objects.filter(mentee=self).order_by('-score'))"

**Comment by harrychen0702** [comment]
the match function looks fine, but why not return the highest 3 mentors for each mentee in the function?

**Comment by mbellgb** [comment]
@harrychen0702 

>Not really understand the "return list(MentorshipScore.objects.filter(mentee=self).order_by('-score'))"

`MentorshipScore` is an object that represents the compatibility score between a mentor and mentee pairing, given a certain programme.

This line of code finds all of the `MentorshipScore` objects in the database where the participant in question is the mentee in the relationship, and orders the results by score in descending order. So essentially, given a mentee, it returns a list of matches from most suitable to least suitable.

>the match function looks fine, but why not return the highest 3 mentors for each mentee in the function?

This will most likely be the case in API methods, this is just for internal use mainly. So when the client access the endpoint (not yet defined), it'll receive the top three.

**Comment by mbellgb** [comment]
Some refactoring of the `Cohort.match()` method.

```python
class Cohort:
  def match(self):
    # Select all mentees, create a MentorshipScore object for each mentor.
    mentors = self.participants.filter(isMentor=True)
    for mentee in self.participants.filter(isMentor=False):
      for mentor in mentors:
        p = MentorshipScore.objects.create(\
          mentor=mentor,
          mentee=mentee,
        )
        p.calculateScore()

class MentorshipScore():
  def calculateScore(self):
    mentee_tags = list(self.mentee.tags.all())
    mentor_tags = list(self.mentor.tags.all())
    self.score = len(set(mentee_tags).intersection(mentor_tags))
    self.save()
```
