### ISSUE TITLE
Cohort register data problem

### ISSUE THREAD

**Issue by harrychen0702** [mbellgb/syseng19-code#6]
Once the user logged in and go to create a new program, the server side should recognise whether the user is admin or not (by token), not  by adding userID into data sent to the server

**Comment by mbellgb** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Cohort register data problem](https://trello.com/c/yNMGNl4Q/61-cohort-register-data-problem)

**Comment by mbellgb** [comment]
@harrychen0702, created a pull request for the programme creation endpoint. haven't done the same for the cohort creation endpoint yet since it's not in master, I'll just make sure it's included in the first version.
